### ISSUE TITLE
Fundamental representation of music

### ISSUE THREAD

**Issue by gogins** [ricktaube/musx#1]
I hope you don't mind me opening an issue here so that we have a record of discussions. 

I have looked at Note.

This is definitely better but I have some minor suggestions that I think would make the representation more usable in more use cases for more people.

There's a conflict between amp (in the interval [0,1]) and off (in [0, 127]). I think amp should also be in the interval [0, 127]. In any event I think the two should be consistent.

I don't think channel should be in [0, 15] but in [0, inf). It can be limited, truncated, or wrapped around on translation to MIDI. Channel should also be int or float. Only int makes sense for MIDI but float makes sense for Csound and maybe for other systems as well. (In Csound, fractional instrument numbers can be used to tie successive notes within the same instrument instance).

Consider changing tuning to divisions_per_semitone. Also, I hope that key.cc goes as is into Csound and does not use the tuning system used for MIDI.

**Comment by ricktaube** [comment]
i was thinking about some of this as i was converting but didn't really get to it yet.
1. since Note is more general maybe 'amp' should just always be 0-1 and then scaled appropriately when converted to midi. Alternately I guess could provide an separate init arg 'vel' that would expect 0-127.  i dont like the idea of 'amp' being more than 1 in a non-midi context because if someone is doing audio that will be a clip and could actually damage speaker or ear.
2.  The name 'chan' is also midi specific.  It could be  'ins' or 'part' or something like that.
3. Also the parameter name 'key' doesn't work if its not midi.  Perhaps it could be 'pitch' or 'freq'. 
4. the 'off' parameter should probably go away since Note is not a midi object. Note could just turn off midi using 127, as people do 99.99999% of the time. After all its always possible to add a MidiEvent::noteon() MidiEvent::noteoff() the the score make one.
5. maybe 'tuning' could be 'dps' or 'semidivs' ???

**Comment by gogins** [comment]
Thanks for your response.

In general I prefer to avoid abbreviations in favor of complete words, and
I prefer to avoid comments in favor of readable code. Of course the code is
yours. That said...

1. I agree, "amplitude" in [0,1] if "off" goes away.

2. I suggest "instrument" in [0, inf).

3. I suggest "pitch" in [0, 127] with the same values as MIDI but allowing
fractions.

4. Yes, that solves 2 problems.

5. I prefer to avoid abbreviations...

Best,
Mike

-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by gogins** [comment]
I would add, there's a semantic ambiguity with "amplitude" and "midi
velocity." These could be either linear or logarithmic. Subjectively of
course the loudness of sounds is logarithmic. It doesn't matter what you
do, although I prefer to use a logarithmic, dBSPL like scale, but it should
be clear to the coder and user whether values are expected to be linear or
logarithmic.

-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by gogins** [comment]
I have created a mike-dev branch off of rick-dev.

I see that the Note class still implements a specifically MIDI-based form of microtonality. I suggest that you remove the tuning and _microtune members of the Note class and just let pitch be pitch, i.e. a quarter tone above middle C is 60.5.

The tuning and _microtune logic should then be refactored into the MidiFile class, and be invoked only when actually rendering the tracks as MIDI messages or MIDI files.

This permits musx to be used without limitation in computer music systems that have more general and powerful representations of notes, such as Csound or SuperCollider.

**Comment by gogins** [comment]
I have updated csound.py in mike-dev to work with recent changes in rick-dev.
